version: 0.2

phases:
  # install node version 12
  install:
    runtime-versions:
      nodejs: 12
  # install dependencies for our node app
  pre_build:
    commands:
      - echo Installing dependencies
      - npm install
  # build stage: for now just run the test
  build:
    commands:
      - echo Running tests
      - npm test
      - echo Building and tagging Docker image
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 504857465313.dkr.ecr.us-east-2.amazonaws.com
      - docker build -t cicddockerimage .
      - docker tag cicddockerimage:latest 504857465313.dkr.ecr.us-east-2.amazonaws.com/cicddockerimage:latest

  post_build:
    commands:
      - echo Pushing to ECR 
      - docker push 504857465313.dkr.ecr.us-east-2.amazonaws.com/cicddockerimage:latest
      # need to add an imagedefinition to tell ecs which task to run upon each Deployment (which we will set up later)
      - printf '[{"name":"CICDDocker", "imageUri":"504857465313.dkr.ecr.us-east-2.amazonaws.com/cicddockerimage:latest"}]' > imagedefinitions.json

# Now add this file as the artifact, aws uses an s3 bucket to store this file during build and read from the file during deployment!
artifacts:
  files:
    - imagedefinitions.json
